### ISSUE TITLE
"Hide passed tests" checkbox not hidding passed tests

### ISSUE THREAD

**Issue by lechu90** [Krinkle/qunit-theme-ninja#4]
When I checked "Hide passed tests" checkbox nothing happen.

Should hide all passed test.

**Comment by Krinkle** [comment]
Can you confirm that this functionality works for you at <https://krinkle.github.io/qunit-theme-ninja/test/>?

**Comment by lechu90** [comment]
I recheck this today. Functionality works for me at page from link. 
It was problem with my local environment only. I used QUnit 1.14.0 and only with this version bug exists (so my pull request is bugfix only if someone use this version ;p). 
After change lib qunit.js to QUnit 2.9.2 functionality works great in my project too.
